#!/bin/bash

# arguments are somewhere/file.pdf

set -e

LTX="pdflatex -synctex=1 -interaction=batchmode"
ZIP="zip -q"
for pdfname in $*; do
    (
    filename="${pdfname##*/}"
    basename="${filename%.pdf}"
    dir="${pdfname%/*}"
    echo $dir $basename
    texfile="$dir/$basename.tex"
    ls "$texfile"  # cheap way to check existence
    cd "$dir"
    GITSTATUS=`git status --porcelain "$basename.tex"`
    echo "%%% This file is generated by Makefile." > vc.tex
    echo "%%% Do not edit this file!\n%%%" >> vc.tex
    git log -1 --format="format:\\gdef\\GITAbrHash{%h $GITSTATUS}\\gdef\\GITAuthorDate{%ad}\\gdef\\GITAuthorName{%an}" -- "$basename.tex"  >> vc.tex
#    echo "\\gdef\\GITAbrHash{XX}\\gdef\\GITAuthorDate{ad}\\gdef\\GITAuthorName{an}"  >> vc.tex
    while (${LTX} "$basename" ; grep -q "Rerun to get" $basename.log ) do true ; done;
    echo
    if [ -e ../../bitbucketLogin.sh ]; then
        . ../../bitbucketLogin.sh
        if [ -z "$GITSTATUS" ]; then
            echo uploading $basename.pdf
            curl -s -u $BITBUCKETLOGIN -X POST "https://api.bitbucket.org/2.0/repositories/rikj/bads-labs/downloads" -F files=@"$basename.pdf"
        #else
            #touch -m -r "$basename.tex" "$basename.pdf"
            #touch -A -01 "$basename.pdf"
        else
            echo uncommited changes -- not uploading $basename.pdf
        fi
    fi
    cd ..
    if [ -d data -o -d src ]; then
        cd ..
        if [ -d $basename ]; then
            # pwd
            GITSTATUS=`git status --porcelain ${basename}`
            shopt -s nullglob
            echo ${ZIP} $basename.zip $basename/data/* $basename/src/* $basename/src/*Sol/* $basename/docs/*.{pdf,tex}
            ${ZIP} $basename.zip $basename/data/* $basename/src/* $basename/src/*Sol/* $basename/docs/*.{pdf,tex}
            if [ -e bitbucketLogin.sh ]; then
                . bitbucketLogin.sh
                echo "$GITSTATUS"
                if [ -z "$GITSTATUS" ]; then
                    echo uploading $basename.zip
                    curl -s -u $BITBUCKETLOGIN -X POST "https://api.bitbucket.org/2.0/repositories/rikj/bads-labs/downloads" -F files=@"$basename.zip"
                else
                    echo uncommited changes -- not uploading $basename.zip
                fi
            fi
        fi
    fi
    )
done
               
